[package]
name = "page-bordering"
version = "1.0.0"
entrypoint = "src/page-bordering.typ"
authors = ["Shumpei Tanaka"]
license = "MIT"
description = "Way to write border around page margin and header/footer."
homepage = "https://shumpei-tanaka.github.io/"
repository = "https://github.com/Shumpei-Tanaka/typst-page-bordering"
categories = ["layout", "office", "report"]
compiler = "0.12.0"
exclude = ["examples", "makefile", "assets"]

[template]
path = "template"
entrypoint = "page-bordering-example.typ"
thumbnail = "assets/page-bordering-example-table-header-footer.png"
